
package com.lhb.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsService", targetNamespace = "http://ws.lhb.com", wsdlLocation = "http://localhost:8080/ws/api?wsdl")
public class WsService_Service
    extends Service
{

    private final static URL WSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSERVICE_EXCEPTION;
    private final static QName WSSERVICE_QNAME = new QName("http://ws.lhb.com", "WsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/api?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVICE_WSDL_LOCATION = url;
        WSSERVICE_EXCEPTION = e;
    }

    public WsService_Service() {
        super(__getWsdlLocation(), WSSERVICE_QNAME);
    }

    public WsService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICE_QNAME, features);
    }

    public WsService_Service(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICE_QNAME);
    }

    public WsService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICE_QNAME, features);
    }

    public WsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsService
     */
    @WebEndpoint(name = "WsServiceImplPort")
    public WsService getWsServiceImplPort() {
        return super.getPort(new QName("http://ws.lhb.com", "WsServiceImplPort"), WsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsService
     */
    @WebEndpoint(name = "WsServiceImplPort")
    public WsService getWsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lhb.com", "WsServiceImplPort"), WsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICE_EXCEPTION!= null) {
            throw WSSERVICE_EXCEPTION;
        }
        return WSSERVICE_WSDL_LOCATION;
    }

}
